### PR TITLE
Change hard-coded LIBROLE_CONFIG definitions in glob.h to functions

### PR DESCRIPTION
**Pull request by ghost**
It was needed to change `LIBROLE_CONFIG` and `LIBROLE_CONFIG_DIR` to
functions in order to allow path substitutions and mocking for
testing purposes.

### CODE REVIEW

**Comment by ghost** [comment]
Ideally, I can compare the resulting file contents but I'm not sure if it is necessary.

**Comment by ghost** [comment]
I strongly believe that inability to perform `librole_ver_free(test_role);` after `librole_role_set(...);` call is a **BUG**.

**Comment by ghost** [comment]
Also operation on strings using `drop_quotes()` looks suspicious.

**Review by vitlav — APPROVED** [review]

**Comment by mastersin** [comment]
Merge with latest fixes in separate branch:
https://github.com/Etersoft/libnss-role/tree/testing-merged

**Comment by mastersin** [comment]
Without this commit latest write test failed: 83a396398567f8b1faf3a45f8bbb9a2bd9f8a73b.

**Comment by mastersin** [comment]
Without this commit test don't run during build with gear-rpm: 67ab89c87e380b10a5a7476e3c3188d03c1226c4.

**Review by mastersin — CHANGES_REQUESTED** [review]
Two latest patches should be applied in this branch, I think.

**Comment by ghost** [comment]
@mastersin , please review the last commit.

**Comment by ghost** [comment]
> Without this commit latest write test failed: [83a3963](https://github.com/Etersoft/libnss-role/commit/83a396398567f8b1faf3a45f8bbb9a2bd9f8a73b).

You need to check the value of struct pointer too. The reason no one had problems with this pointer is because you allocate `struct librole_ver` on stack but you will have problems in case of allocation on heap.

**Comment by ghost** [comment]
> Without this commit test don't run during build with gear-rpm: [67ab89c](https://github.com/Etersoft/libnss-role/commit/67ab89c87e380b10a5a7476e3c3188d03c1226c4).

There is already **RPATH** present in `test_main` without special flags.

**Comment by ghost** [comment]
I introduced `nss_wrapper` to run tests with fake files but, interestingly, `librole_reading()` fails in case it encounters non-existing groups like "domain admins".

**Comment by ghost** [comment]
> I introduced `nss_wrapper` to run tests with fake files but, interestingly, `librole_reading()` fails in case it encounters non-existing groups like "domain admins".

I'm not sure if it is a bug or not.

**Comment by ghost** [comment]
I have eliminated extra `fail_msg()` calls in order to allow to free memory after setup errors.

**Pull request merged**
